apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::262370815850:role/EKS-Demo-Node-NodeInstanceRole-KS7XQETPQS3V
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::262370815850:user/Siddhi
      username: eks-k8s
      groups:
        - system:masters
